-- Generated by scripts/generate-licenses.js
-- Review email/max_devices/expires_at values before running in Supabase
INSERT INTO license_keys (key, email, max_devices, expires_at) VALUES
('INKF-U3VN-HR6G-EWXF', 'sales@yourdomain.com', 2, NULL),
('INKF-MA42-KEBN-4BHA', 'sales@yourdomain.com', 2, NULL),
('INKF-JP3S-4WFQ-QJRB', 'sales@yourdomain.com', 2, NULL),
('INKF-N4PE-3E9L-Z4TD', 'sales@yourdomain.com', 2, NULL),
('INKF-7G68-FFY2-DH6Q', 'sales@yourdomain.com', 2, NULL),
('INKF-DV6X-5JRL-6QC7', 'sales@yourdomain.com', 2, NULL),
('INKF-FT42-8SS6-B8V3', 'sales@yourdomain.com', 2, NULL),
('INKF-PHGC-LHRV-J24X', 'sales@yourdomain.com', 2, NULL),
('INKF-DYJW-MAY7-DJ82', 'sales@yourdomain.com', 2, NULL),
('INKF-279P-S5SN-BZWD', 'sales@yourdomain.com', 2, NULL),
('INKF-D95N-ATYR-JALH', 'sales@yourdomain.com', 2, NULL),
('INKF-97YD-6HCB-3K5E', 'sales@yourdomain.com', 2, NULL),
('INKF-EVUB-56XG-46KT', 'sales@yourdomain.com', 2, NULL),
('INKF-9GAR-7WYH-ZKLT', 'sales@yourdomain.com', 2, NULL),
('INKF-4GGV-H99D-FVPB', 'sales@yourdomain.com', 2, NULL),
('INKF-Z99V-XJNV-H2SV', 'sales@yourdomain.com', 2, NULL),
('INKF-V4VM-LNCR-UWH4', 'sales@yourdomain.com', 2, NULL),
('INKF-K375-TQCS-Y3SR', 'sales@yourdomain.com', 2, NULL),
('INKF-VLF9-U7VR-X3MP', 'sales@yourdomain.com', 2, NULL),
('INKF-VLJG-8RFY-GRDW', 'sales@yourdomain.com', 2, NULL);
